services:
  - type: web
    name: vietqr-telegram-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VIETQR_CLIENT_ID
        sync: false
      - key: VIETQR_API_KEY
        sync: false 